server.port=8081
spring.application.name=user-service

# Actuator — expose health + prometheus metrics endpoints
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true

# Info endpoint
info.app.name=user-service
info.app.version=@project.version@
